---
title: "useso_autograder"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(googlesheets4)
```

```{r}
# Constant Sheet Parameters
id_students <- 
  "REDACTED"
students_sheet <- "parseable"

id_exam_scores <- "1SxvZEQ4OuLvUywl8P15jeACnAdj8H5zMjr-cidvH_JI"
all_exams_name <- "All Exams"

# Exam Parameters
# Practice 1KMEG7VwNhwdmPMEja1EQb50D6KEWQ7ZyhiplR46XnQw
# R&M 1sML9Fz-Qyn8xxJYYfh4qAEu-429ogiU3H0ih0YxVl-8
id_exam_sheet <- 
  "1fny5u8Rx3xUgGN4Uakog3cvzoJtzJaKlq5HKXOAEbfE"

exam_name <- "Geosphere Exam"
exam_length <- 60
exam_penalty <- 0 # fraction between 0 and 1

exam_start <- mdy_hm("7/7/2020 1:00 PM", tz = "America/New_York")
timestamp_tz <- "America/Los_Angeles"


diff_start <- 
  tribble(
    ~color, ~diff,
    "red", 0,
    "orange", 0,
    "yellow", 0,
    "green", 0,
    "blue", 0, 
    "violet", 0, 
    "indigo", 0,
    "pink", 0
  )

# Grading Parameters
single_point <- 1
multi_point <- 1
multi_extra_penalty <- 1

exam_weights <- 
  tribble(
    ~name, ~weights,
    "R&M Exam", 1,
    "Geosphere Exam", 1
  )
```

```{r}
format_cols <- function(df) {
  df %>% 
    rename_all(
      ~ str_to_lower(.) %>% 
        str_replace_all(" ", "_")
    )
}

read_exam_scores <- function(name, weight) {
  weighted = str_c(name, "_weighted")
  id_exam_scores %>% 
    read_sheet(sheet = name) %>% 
    format_cols() %>% 
    transmute(
      name, 
      color, 
      {{name}} := score, 
      {{weighted}} := score * weight
    ) %>% 
    format_cols()
}

get_weights <- function(name) {
  id_exam_scores %>% 
    read_sheet(sheet = name) %>% 
    format_cols() %>%
    summarize(weights = 50 / median(score, na.rm = TRUE)) %>% 
    mutate(name = name) %>% 
    select(name, everything())
}
```

```{r}
student_color <- 
  id_students %>% 
  read_sheet(sheet = students_sheet) %>% 
  format_cols() %>% 
  left_join(diff_start, by = "color") %>% 
  mutate(
    color = 
      factor(
        color, 
        levels = diff_start$color
      )
  )

exam_response <- 
  id_exam_sheet %>% 
  read_sheet() %>% 
  format_cols() %>% 
  drop_na(name) %>% 
  mutate(timestamp = force_tz(timestamp, timestamp_tz))
```

```{r}
# Practical Exam, duration only
# exam_response %>% 
#   select(timestamp, name) %>% 
#   left_join(student_color, by = "name") %>% 
#   drop_na(color) %>% 
#   mutate(
#     duration = 
#       as.integer(60 * (timestamp - (exam_start + minutes(diff)))),
#     minutes_over = as.integer((duration - exam_length * 60) / 60),
#     duration = as.integer(duration / 60)
#   ) %>% 
#   select(name, color, duration) %>% 
#   arrange(color, name) %>% 
#   sheet_write(ss = id_exam_scores, sheet = exam_name)
```

```{r}
# Theoretical Exams, duration and scoring
key <- 
  exam_response %>% 
  pivot_longer(
    cols = -c("timestamp", "name"),
    names_prefix = "question_",
    names_to = "question",
    values_to = "response"
  ) %>%
  filter(name == "ANSWER_KEY") %>% 
  select(question, key_response = response)

all_scores <- 
  exam_response %>% 
  pivot_longer(
    cols = -c("timestamp", "name"),
    names_prefix = "question_",
    names_to = "question",
    values_to = "response"
  ) %>%
  filter(name != "ANSWER_KEY") %>% 
  left_join(key, by = "question") %>% 
  left_join(student_color, by = "name") %>% 
  mutate(
    duration = 
      as.integer(60 * (timestamp - (exam_start + minutes(diff)))),
    key_response = str_replace_all(key_response, " ", "") %>% str_split(","),
    response = 
      str_replace_all(response, " ", "") %>% 
      str_to_upper() %>% 
      str_split(","),
    correct = 
      map2(response, key_response, intersect) %>% map(length) %>% unlist(),
    extra = map2(response, key_response, setdiff) %>% map(length) %>% unlist(),
    num_choices = key_response %>% map(length) %>% unlist(),
    raw_score = 
      if_else(
        num_choices == 1, 
        single_point * correct - multi_extra_penalty * extra,
        multi_point * correct - multi_extra_penalty * extra
      ),
    score = if_else(raw_score < 0, 0, raw_score)
  )

scores <- 
  all_scores %>% 
  count(timestamp, duration, color, name, wt = score, name = "score") %>%
  mutate(
    minutes_over = as.integer((duration - exam_length * 60) / 60),
    score =
      if_else(
        minutes_over > 0,
        score * (1 - exam_penalty * minutes_over),
        score
      ),
    duration = as.integer(duration / 60)
  ) %>% 
  select(color, name, duration, score) %>% 
  arrange(color, name)

scores %>% 
 sheet_write(ss = id_exam_scores, sheet = exam_name)
```

```{r}
exam_weights <- 
  exam_weights %>%
  pull(name) %>% 
  map_dfr(get_weights)

exam_weights %>%
  mutate(weighted = map2(name, weights, read_exam_scores)) %>% 
  pull(weighted) %>% 
  reduce(left_join, by = c("name", "color")) %>% 
  mutate(
    all_exams_weighted = reduce(select(., ends_with("_weighted")), `+`)
  ) %>% 
  arrange(desc(all_exams_weighted)) %>% 
  sheet_write(ss = id_exam_scores, sheet = all_exams_name)
```

```{r}
key %>% 
  mutate(
    key_response = str_replace_all(key_response, " ", "") %>% str_split(","),
    max_points = map(key_response, length) %>% unlist()
  ) %>% 
  summarize(max_correct = sum(max_points))
```

```{r}
scores %>% 
  summary()
```

